export const ADD_COUNTER = "ADD_COUNTER";
export const REMOVE_COUNTER = "REMOVE_COUNTER";

export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCTS_SUCCESS";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCTS_SUCCESS";